### user register
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "firstName":"Vindhya",
    "lastName":"Enikapally",
    "email":"vindhyaa@gmail.com",
    "password":"vindhya@123",
    "profileImageUrl":"https://example.com/avatars/author.png"
}

###user login
POST http://localhost:4000/common-api/authenticate
Content-Type: application/json

{
    "email":"vindhya@gmail.com",
    "password":"vindhya@123",
    "role":"USER"
}

### author register
POST http://localhost:4000/author-api/users
Content-Type: application/json

{
    "firstName":"Vindhuu",
    "lastName":"Author",
    "email":"vindhuu.author@gmail.com",
    "password":"vindhuu@123",
    "profileImageUrl":"https://example.com/avatars/author.png"
}

### author login
POST http://localhost:4000/common-api/authenticate
Content-Type: application/json

{
    "email":"vindhuu.author@gmail.com",
    "password":"vindhuu@123",
    "role":"AUTHOR"
}

###create article
POST http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "author":"69896e057f6dc48450c4d5d2",
    "title":"test1 article",
    "category":"programming",
    "content":"content of test1 article"
}

###read articles
GET http://localhost:4000/author-api/articles/69896e057f6dc48450c4d5d2

### update article
PUT  http://localhost:4000/author-api/articles/6989763a5199ebb6ec345fb1
Content-Type: application/json

{
    "author":"69896e057f6dc48450c4d5d2",
    "title":"test1 article",
    "category":"programming",
    "content":"content of test1 article..."
}

###logout
POST http://localhost:4000/common-api/logout

###invalid request
GET http://localhost:4000/test

###invalid request
GET http://localhost:4000/hello

### ================= ADMIN =================

### admin register (run only once if not created)
POST http://localhost:4000/admin-api/users
Content-Type: application/json

{
    "firstName":"Admin",
    "lastName":"User",
    "email":"admin@gmail.com",
    "password":"admin@123"
}

### admin login
POST http://localhost:4000/common-api/authenticate
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"admin@123",
    "role":"ADMIN"
}

### block user (ADMIN must login first)
PUT http://localhost:4000/admin-api/block-user/698ddaccdb92fd2dd15689ff

### unblock user (ADMIN must login first)
PUT http://localhost:4000/admin-api/unblock-user/698ddaccdb92fd2dd15689ff
